[project]
name = "cambridge-battlecode-26"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12.3"
dependencies = [
    "anthropic>=0.92.0",
    "cambc==1.7.0",
    "numpy>=2.4.4",
    "pre-commit>=4.5.1",
    "pyright>=1.1.408",
    "python-dotenv>=1.2.2",
    "voyageai>=0.3.7",
]
